baseURL = "https://blog.turingchallenge.com/"
languageCode = "es-es"
title = "Turing Challenge - Blog"

theme = "story"

pygmentsCodeFences = true
pygmentsUseClasses = true

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML", "JSON"]