baseURL = "https://turing-blog.netlify.com/"
languageCode = "es-es"
title = "turing - blog"

theme = "story"

pygmentsCodeFences = true
pygmentsUseClasses = true

image = "/img/default-header-img.png"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML", "JSON"]