baseURL = "https://blog.turingchallenge.com/"
languageCode = "es-es"
#title = ""

theme = "story"

pygmentsCodeFences = true
pygmentsUseClasses = true

image = "/img/default-header-img.png"

googleAnalytics = "UA-102023885-4"
disqusShortname = "turing-blog"

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]

[Params]
  author = "Turing Challenge"
  authorUrl = "https://www.turingchallenge.com/"
